project_id = "cchhvuotfdxswpxwnxgv"

[functions.validate-invite]
verify_jwt = false

[functions.evaluate-answer]
verify_jwt = false

[functions.notify-test-complete]
verify_jwt = false

[functions.send-invitation-email]
verify_jwt = false

[functions.send-design-update-email]
verify_jwt = false
